# Generated by Django 4.0.6 on 2022-08-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('fb_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, default='START', max_length=50)),
                ('query', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('normaluser', 'normaluser')], default='normaluser', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('verifier', models.BooleanField()),
                ('zone', models.IntegerField(choices=[(1, 'Zone1'), (2, 'Zone2'), (3, 'Zone3'), (4, 'Zone4'), (5, 'Zone5'), (6, 'Zone6')], default=1)),
                ('publier_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CentreMedical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('verifier', models.BooleanField()),
                ('zone', models.IntegerField(choices=[(1, 'Zone1'), (2, 'Zone2'), (3, 'Zone3'), (4, 'Zone4'), (5, 'Zone5'), (6, 'Zone6')], default=1)),
                ('publier_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.utilisateur')),
            ],
        ),
    ]
